proj_name: ???

link_image_dir: True
verbose: False

hydra:
  run:
    dir: ./projects/${now:%Y-%m-%d}/${proj_name}

images: ???
is_nomask: False
is_simplemask: False
masks: ???

matcher: ???  # '32K', '256K', '1M', 
              # 'SEQ', 'SEQ-32K', 'SEQ-256K', 'SEQ-1M'

# For sequential matching, 
#   `overlap` is important, default 10
#   can also perform vocab tree matching, 
#   `loop_detection_period`, every 10 frames

# For vocab matching, 
#   `num_images` default 100
#   VocabTreeMatching.match_list_path can set matching images


hierarchical_mapper: False

camera_model: 'SIMPLE_RADIAL'
