proj_name: ???

link_image_dir: True
verbose: False

hydra:
  run:
    dir: ./projects/${now:%Y-%m-%d}/${proj_name}

images: ???
is_nomask: False
is_simplemask: False
masks: ???

matcher: ???  # '32K', '256K', '1M', 
              # 'SEQ', 'SEQ-32K', 'SEQ-256K', 'SEQ-1M'

hierarchical_mapper: False

camera_model: 'SIMPLE_RADIAL'
